// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAehybWM3_vYntsXTWSiYqWBY00pPIUSI',
    appId: '1:286777752164:web:fd879627ac9b592a63bd71',
    messagingSenderId: '286777752164',
    projectId: 'hifyp-ea16a',
    authDomain: 'hifyp-ea16a.firebaseapp.com',
    storageBucket: 'hifyp-ea16a.firebasestorage.app',
    measurementId: 'G-DSPD2GNGWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhprBpAfBNY6__VX79pbOyog9TU62ykw',
    appId: '1:286777752164:android:2ca39b32dd9c53aa63bd71',
    messagingSenderId: '286777752164',
    projectId: 'hifyp-ea16a',
    storageBucket: 'hifyp-ea16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNdc_Uik6UQ0EOVG0sxcnebAzsNE52t8',
    appId: '1:286777752164:ios:da0cb8f8395e7e5a63bd71',
    messagingSenderId: '286777752164',
    projectId: 'hifyp-ea16a',
    storageBucket: 'hifyp-ea16a.firebasestorage.app',
    iosClientId: '286777752164-makquuhko1010mi7scqd5tph8shq84j1.apps.googleusercontent.com',
    iosBundleId: 'com.edu.tarumt.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNdc_Uik6UQ0EOVG0sxcnebAzsNE52t8',
    appId: '1:286777752164:ios:da0cb8f8395e7e5a63bd71',
    messagingSenderId: '286777752164',
    projectId: 'hifyp-ea16a',
    storageBucket: 'hifyp-ea16a.firebasestorage.app',
    iosClientId: '286777752164-makquuhko1010mi7scqd5tph8shq84j1.apps.googleusercontent.com',
    iosBundleId: 'com.edu.tarumt.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAehybWM3_vYntsXTWSiYqWBY00pPIUSI',
    appId: '1:286777752164:web:e31c96799df1cb4163bd71',
    messagingSenderId: '286777752164',
    projectId: 'hifyp-ea16a',
    authDomain: 'hifyp-ea16a.firebaseapp.com',
    storageBucket: 'hifyp-ea16a.firebasestorage.app',
    measurementId: 'G-Y5H72RR3FC',
  );
}
